#ifndef __YroJackGuitarMainWindow__
#define __YroJackGuitarMainWindow__

/**
 @file
 Subclass of MainWindow, which is generated by wxFormBuilder.
 */

#include <jack/YroJackDriver.h>
#include <jack/YroEffectFactory.h>
#include <plugins/YroEffectPlugin.h>

#include <wx/custom/WxEffect.h>

#include <wx/YroJackGuitarEffectCtrl.h>
#include <wx/YroJackGuitarGeneral.h>
#include <wx/YroJackGuitarSignalFrame.h>
#include <wx/YroJackGuitarEffectDistortion.h>
#include <wx/YroJackGuitarEffectExpander.h>
#include <wx/WxMainTimer.h>

namespace std {

/** Implementing MainWindow */
class YroJackGuitarMainWindow: public MainWindow {
protected:
	// Handlers for MainWindow events.
	void OnClose(wxCloseEvent& event);
	void OnConnect(wxCommandEvent& event);
	void onPaintEffects( wxPaintEvent& event );
public:
	/** Constructor */
	static YroJackGuitarMainWindow *instance() {
		if (__instance == 0) {
			__instance = new YroJackGuitarMainWindow(0);
		}
		return __instance;
	}
	virtual ~YroJackGuitarMainWindow();
	void OnJackNewAudioSample();
	void OnJackConnect();
	void synchronizeWithPluginFactory();
	wxFrame *getFrame(YroEffectPlugin *plugin);
private:
	YroJackGuitarMainWindow(wxWindow* parent);
	static YroJackGuitarMainWindow *__instance;
	WxMainTimer timer;
	/**
	 * effects table
	 */
	map<YroEffectPlugin *, wxFrame *> myJackEffects;
	vector<YroJackGuitarEffectCtrl *> myEffects;
};

}
#endif // __YroJackGuitarMainWindow__
