#ifndef __YroJackGuitarEffectDistortion__
#define __YroJackGuitarEffectDistortion__

/**
@file
Subclass of EffectDistortion, which is generated by wxFormBuilder.
*/

#include "WxApp.h"
#include <plugins/distortion/Distortion.h>
#include <wx/YroJackGuitarEffectDistortion.h>

using namespace std;

/** Implementing EffectDistortion */
class YroJackGuitarEffectDistortion : public EffectDistortion
{
protected:
	// Handlers for EffectDistortion events.
	void onChangePreset( wxCommandEvent& event );
	void onChangeWetDry( wxScrollEvent& event );
	void onChangeLRCross( wxScrollEvent& event );
	void onChangeDrive( wxScrollEvent& event );
	void onChangeLevel( wxScrollEvent& event );
	void onChangeType( wxCommandEvent& event );
	void onChangeNegate( wxCommandEvent& event );
	void onChangePrefilter( wxCommandEvent& event );
	void onChangeStereo( wxCommandEvent& event );
	void onChangePanning( wxScrollEvent& event );
	void onChangeSubOctave( wxScrollEvent& event );
	void onChangeLpf( wxScrollEvent& event );
	void onChangeHpf( wxScrollEvent& event );
	
public:
	/** Constructor */
	YroJackGuitarEffectDistortion(wxWindow* parent, Distortion *_effect);

private:
	Distortion *effect;
};

#endif // __YroJackGuitarEffectDistortion__
