#ifndef __YroJackGuitarEffectDistortion__
#define __YroJackGuitarEffectDistortion__

/**
@file
Subclass of EffectDistortion, which is generated by wxFormBuilder.
*/

#include "WxApp.h"

/** Implementing EffectDistortion */
class YroJackGuitarEffectDistortion : public EffectDistortion
{
protected:
	// Handlers for EffectDistortion events.
	void OnSpinCtrl( wxSpinEvent& event );
	void OnSpinCtrlText( wxCommandEvent& event );
	void OnChoice( wxCommandEvent& event );
	
public:
	/** Constructor */
	YroJackGuitarEffectDistortion( wxWindow* parent );

private:
	std::Distortion *effect;
};

#endif // __YroJackGuitarEffectDistortion__
