#ifndef __YroJackGuitarEffectDistortion__
#define __YroJackGuitarEffectDistortion__

/**
@file
Subclass of EffectDistortion, which is generated by wxFormBuilder.
*/

#include "WxApp.h"
#include <plugins/effect/Distortion.h>
#include <wx/YroJackGuitarEffectDistortion.h>

using namespace std;

/** Implementing EffectDistortion */
class YroJackGuitarEffectDistortion : public EffectDistortion
{
protected:
	// Handlers for EffectDistortion events.
	void OnChoice( wxCommandEvent& event );
	
public:
	/** Constructor */
	YroJackGuitarEffectDistortion(wxWindow* parent, Distortion *_effect);

private:
	Distortion *effect;
};

#endif // __YroJackGuitarEffectDistortion__
