#ifndef __YroJackGuitarResource__
#define __YroJackGuitarResource__

/**
 @file
 Subclass of Resource, which is generated by wxFormBuilder.
 */

#include "WxApp.h"

/** Implementing Resource */
class YroJackGuitarResource: public Resource {
public:
	/** Constructor */
	YroJackGuitarResource(wxWindow* parent);
	wxMenu* getPopup1() const;
};

#endif // __YroJackGuitarResource__
