#ifndef __YroJackGuitarEffectExpander__
#define __YroJackGuitarEffectExpander__

/**
@file
Subclass of EffectExpander, which is generated by wxFormBuilder.
*/

#include <wx/WxApp.h>
#include <jack/YroEffectFactory.h>

namespace std {

/** Implementing EffectExpander */
class YroJackGuitarEffectExpander : public EffectExpander {
protected:
	// Handlers for EffectExpander events.
	void onActivate( wxCommandEvent& event );
	void onChangePreset( wxCommandEvent& event );
	void onChangeAttack( wxScrollEvent& event );
	void onChangeRelease( wxScrollEvent& event );
	void onChangeShape( wxScrollEvent& event );
	void onChangeThreshold( wxScrollEvent& event );
	void onChangeLevel( wxScrollEvent& event );
	void onChangeLpf( wxScrollEvent& event );
	void onChangeHpf( wxScrollEvent& event );
	
public:
	/** Constructor */
	YroJackGuitarEffectExpander(wxWindow* parent, Expander *_effect);

private:
	Expander *effect;
};

}
#endif // __YroJackGuitarEffectExpander__
