#ifndef __YroJackGuitarSignalFrame__
#define __YroJackGuitarSignalFrame__

#include <wx/wx.h>
#include <jack/YroAudioSampleFactory.h>

/**
 @file
 Subclass of SignalFrame, which is generated by wxFormBuilder.
 */

#include "WxApp.h"

namespace std {

/** Implementing SignalFrame */
class YroJackGuitarSignalFrame: public SignalFrame {
protected:
	// Handlers for SignalFrame events.
	void OnPaint(wxPaintEvent& event);
private:
	YroAudioSampleFactory *audioSampleFactory;
public:
	/** Constructor */
	YroJackGuitarSignalFrame(wxWindow* parent);
	void OnJackNewAudioSample();
};

}

#endif // __YroJackGuitarSignalFrame__
